### ISSUE TITLE
길찾기 API 에러 응답 형식 수정 및 리팩토링

### ISSUE THREAD

**Issue by mungsil** [Chance-Glance/server#20]
## 📄 이슈 내용

- 길찾기 API로 사용하고 있는 `ODsay API`는 `API key` 와 관련된 예외로 다음 응답을 반환합니다.

    > [{"code":"500","message":"[ApiKeyAuthFailed] ApiKey authentication failed."}]    

    
    반면, 출발지와 도착지 사이 거리가 700m 이내인 경우에는 다음 응답을 반환합니다.
    > {"msg":"출, 도착지가 700m이내입니다.","code":"-98"}

    따라서, 현재 출발지와 도착지 사이 거리가 700m 이내인 경우에 반환되는 API 응답을 처리하는 상황에 있어 `NullPointerException`이 발생하고 있습니다. NPE가 발생하지 않도록 에러 응답 형식을 수정합니다.

- 기존 코드는 길찾기 API 예외 발생 시 `RuntimeException`을 `throw`하고 있습니다. 더 명확한 의도 전달과 유지보수성을 위해 전용 커스텀 `Exception`을 정의하고자 합니다.

## 🛠️ Task 목록

이 이슈를 해결하기 위해 필요한 작업(Task)을 목록으로 작성해주세요.

- [x] 에러 응답 형식 수정
- [x] 커스텀 `Exception` 생성
- [x] 가독성 향상을 위해 메서드/파라미터 이름 변경
